Repository dev-protocol/devprotocol.xyz, pull requests merged in 2021-11, with the labels that each got.

#89 fix: Use Yarn commands instead of NPM commands
  .gitpod.yml
  yarn.lock
Labels: enhancement

#91 feat: features section
  src/components/Creators/Features.astro
  src/components/Creators/Hero.astro
  src/pages/creators.astro
Labels: enhancement

#93 Feat center features
  src/components/Creators/Features.astro
  src/components/Creators/Hero.astro
  src/pages/creators.astro
  tailwind.config.js
Labels: enhancement

#92 feat: creators page team section
  src/components/Creators/Features.astro
  src/components/Developers/Features.astro
  src/components/Developers/Hero.astro
  src/components/Developers/Team.astro
  src/pages/creators.astro
  src/pages/developers.astro
  tailwind.config.js
Labels: enhancement

#95 fix: update from `master` to `main` branch
  .github/pull_request_template.md
Labels: bug

#94 fix: spelling errors in the Developers/Features page
  src/components/Developers/Features.astro
Labels: bug

#96 fix: invitation link and improve wording
  CONTRIBUTING.md
Labels: enhancement

#99 fix: Add missing issue forms
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: enhancement

#100 Implement new section (L2), finalize links, use grid-gap instead of padding for each component
  src/components/Home/Banners/L2.astro
  src/components/Home/Hero.astro
  src/components/Home/Heros/Creators.astro
  src/components/Home/Heros/DevToken.astro
  src/components/Home/Heros/Patrons.astro
  src/components/Home/SuccessStories.vue
  src/layouts/Default.astro
  src/pages/index.astro
Labels: enhancement

#97 fix: use Yarn commands in the `README.md` file
  README.md
Labels: bug

#101 fix: Discord invitation link
  README.md
Labels: bug

#98 chore: Open preview instead of a new tab
  .gitpod.yml
Labels: enhancement

#108 chore: Add license and other fields in the `package.json` file
  package.json
Labels: documentation

#114 chore: update the bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: enhancement

#115 fix: Update CoC link in the feature request template
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: bug

#116 fix: add contact links in the configuration template
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement

#113 fix: Update the "use-cases" section
  src/components/Creators/UseCases.astro
Labels: bug

#119 fix: contact link in the issue template configuration
  .github/ISSUE_TEMPLATE/config.yml
Labels: bug

#118 fix: Improve the "Step by Step" section
  src/components/Creators/StepbyStep.astro
Labels: enhancement

#126 feat: welcome first timers
  .github/workflows/first-interaction.yml
Labels: enhancement

#128 fix: Vyper Stakes.Social link
  src/components/Home/SuccessStories.vue
Labels: bug

#132 fix: delete `package-lock.json`
  package-lock.json
Labels: bug

#135 fix: Meta description
  src/layouts/Default.astro
Labels: bug

#137 feat: Improve the greetings/first-timers text
  .github/workflows/first-interaction.yml
Labels: enhancement

#136 Fixed Navbar and Footbar - Mobile View
  src/components/Global/Navigation.astro
  src/layouts/Default.astro
Labels: bug

#139 [FEATURE] loaded SVG files in the footer
  public/assets/medium.svg
  public/assets/twitter.svg
  src/components/Global/Footer.astro
Labels: enhancement

#145 [Feature]: Dark Mode
  public/assets/dark.svg
  public/assets/dropdown-arrow.svg
  public/assets/light.svg
  src/components/Global/Navbar.vue
  src/components/Global/ThemeButton.vue
  src/components/Home/Banners/L2.astro
  src/components/Home/Hero.astro
  src/components/Home/Heros/Creators.astro
  src/components/Home/Heros/DevToken.astro
  src/components/Home/Heros/Patrons.astro
  src/components/Home/Sections/Backers.astro
  src/components/Home/SuccessStories.vue
  src/layouts/Default.astro
  src/styles/global.css
  tailwind.config.js
Labels: enhancement

#149 feat: Redirect to their respective profiles for all the team
  src/components/Developers/Team.astro
Labels: enhancement

#150 feat: Add `og:description`
  src/layouts/Default.astro
Labels: enhancement

#147 Fix Dark Mode
  src/components/Developers/Features.astro
  src/components/Developers/Team.astro
  src/components/Global/Navbar.vue
  src/components/Global/Navigation.vue
  src/layouts/Default.astro
  src/styles/global.css
  tailwind.config.js
Labels: bug

#151 Feature dapps card carousel #131
  package.json
  src/components/Home/Hero.astro
  src/components/Home/Sections/Dapps.astro
  src/components/Home/Sections/Dapps.vue
  src/pages/index.astro
Labels: enhancement

#155 Update first-interaction.yml
  .github/workflows/first-interaction.yml
Labels: bug

#159 feat: Add FAQ page
  src/components/Faq/Faq.vue
  src/components/Global/Navbar.vue
  src/pages/faq.astro
Labels: enhancement

#164 fix: contributing guidelines link
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#163 docs: improve FAQ translation wording
  src/components/Faq/Faq.vue
Labels: documentation

#166 fix: HTML styling in the greetings workflow
  .github/workflows/first-interaction.yml
Labels: bug

#165 [REFACTOR]: FAQ translation management made easier
  package.json
  snowpack.config.js
  src/components/Faq/Faq.vue
  src/components/Faq/lang.csv
  yarn.lock
Labels: enhancement

#158 Krishguptadev/feature-add-community-156
  public/assets/experify.png
  public/assets/msstartups-mark.png
  src/components/Global/Navbar.vue
  src/pages/community-partners.astro
Labels: enhancement

#170 [FIX]: Added missing title in community partners page
  src/pages/community-partners.astro
Labels: bug
