Repository dev-protocol/devprotocol.xyz, pull requests merged in 2021-12, with the labels that each got.

#174 feat: Add intlify to the list of community partners
  src/pages/community-partners.astro
Labels: community-partners

#172 [UPDATE]: Improved the color combination of community partners page in light mode
  src/pages/community-partners.astro
Labels: enhancement

#171 fix: Microsoft for Startups logo being stretched
  public/assets/microsoft.png
  public/assets/microsoft.svg
  src/pages/community-partners.astro
Labels: bug

#180 docs: add `[]` in the PR template...
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#181 [FIX]: Community partners cutoff
  src/pages/community-partners.astro
Labels: bug

#177 [FEATURE]: Add categorical view to FAQ
  src/components/Faq/Faq.vue
  src/components/Faq/lang.csv
  src/styles/global.css
Labels: enhancement

#186 fix: change translate button
  src/components/Faq/Faq.vue
Labels: bug

#191 fix: Microsoft for Startups logo
  public/assets/microsoft.png
Labels: enhancement

#188 [UPDATE]: Add button & Adjust position of Community Partners' description
  src/pages/community-partners.astro
Labels: enhancement

#192 Feature: Add About Page
  src/components/About/About.astro
  src/components/About/Team.astro
  src/components/Faq/lang.csv
  src/components/Global/Navbar.vue
  src/pages/about.astro
  src/pages/developers.astro
Labels: enhancement

#195 fix: remove `package-lock.json` file
  package-lock.json
Labels: bug

#199 [Feature] Add Community Partners form
  astro.config.mjs
  package.json
  postcss.config.cjs
  public/assets/discord.svg
  public/assets/email.png
  public/assets/github.png
  public/assets/phone.png
  public/assets/spinner.png
  snowpack.config.js
  src/components/CommunityPartners/CommunityPartners.vue
  src/components/CommunityPartners/CommunityPartnersModal.vue
  src/components/Faq/Faq.vue
  src/components/Faq/lang.csv
  src/components/Faq/lang.json
  src/components/Home/Sections/Backers.astro
  src/layouts/Default.astro
  src/pages/community-partners.astro
  src/pages/index.astro
  tailwind.config.js
  yarn.lock
Labels: enhancement

#202 Add DEV Shop
  src/components/Global/Navbar.vue
Labels: on-hold
